title: "William F-C"
email: "willfc000@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://williamfc.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: "williamfc.com"

header_pages:
  - about.markdown
  - portfolio.markdown
  - posts.markdown

footer: 'Find me on <a href="https://twitter.com/">twitter</a>'

# Build settings
remote_theme: b2a3e8/jekyll-theme-console
style: hacker

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
